/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetodesoftware.Commissioned;
import projetodesoftware.Funcionario;
import projetodesoftware.Hourly;
import projetodesoftware.QuadrodeFuncionarios; 
import projetodesoftware.Salaried;
/**
 *
 * @author Rangel
 */
public class AddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     * @param qf
     */
    QuadrodeFuncionarios qfmain;
    DefaultTableModel tablemain;
    
    public AddEmployee() {
        initComponents();
    }
    
    public void importQuandroF(QuadrodeFuncionarios qf, DefaultTableModel table){
        qfmain = qf;
        tablemain = table;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        bntAddSalaried = new javax.swing.JButton();
        txtNameSalaried = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAddressSalaried = new javax.swing.JTextField();
        txtSalarySalaried = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtIDSalaried = new javax.swing.JTextField();
        rbtnSyndSalaried = new javax.swing.JRadioButton();
        txtMethodSalaried = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        rbtnChequeCorreio1 = new javax.swing.JRadioButton();
        rbtnChequeMaos1 = new javax.swing.JRadioButton();
        rbtnDepositoBancario1 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        bntAddHourly = new javax.swing.JButton();
        txtNameHourly = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtAddressHourly = new javax.swing.JTextField();
        txtSalaryHourly = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtIDHourly = new javax.swing.JTextField();
        rbtnSyndHourly = new javax.swing.JRadioButton();
        txtMethodHourly = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        rbtnDepositoBancario2 = new javax.swing.JRadioButton();
        rbtnChequeMaos2 = new javax.swing.JRadioButton();
        rbtnChequeCorreio2 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        txtCommission = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bntAddCommissioned = new javax.swing.JButton();
        txtNameCommissioned = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAddressCommissioned = new javax.swing.JTextField();
        txtSalaryCommissioned = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIDCommissioned = new javax.swing.JTextField();
        rbtnSyndCommissioned = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtMethodCommissioned = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        rbtnDepositoBancario3 = new javax.swing.JRadioButton();
        rbtnChequeMaos3 = new javax.swing.JRadioButton();
        rbtnChequeCorreio3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel13.setText("Nome:");

        bntAddSalaried.setText("Adicionar");
        bntAddSalaried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddSalariedActionPerformed(evt);
            }
        });

        jLabel14.setText("Salario");

        jLabel15.setText("Endereço");

        jLabel17.setText("CPF");

        rbtnSyndSalaried.setText("Sindicato");
        rbtnSyndSalaried.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rbtnSyndSalaried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSyndSalariedActionPerformed(evt);
            }
        });

        txtMethodSalaried.setEditable(false);
        txtMethodSalaried.setText("mensalmente");
        txtMethodSalaried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMethodSalariedActionPerformed(evt);
            }
        });

        jLabel23.setText("Método");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel27.setText("Pagamento via:");

        rbtnChequeCorreio1.setText("Cheque pelos correios");
        rbtnChequeCorreio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnChequeCorreio1ActionPerformed(evt);
            }
        });

        rbtnChequeMaos1.setText("Cheque em mãos");
        rbtnChequeMaos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnChequeMaos1ActionPerformed(evt);
            }
        });

        rbtnDepositoBancario1.setText("Deposito Bancario");
        rbtnDepositoBancario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDepositoBancario1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIDSalaried, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSalarySalaried, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMethodSalaried, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rbtnSyndSalaried)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(bntAddSalaried))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnChequeMaos1)
                            .addComponent(rbtnChequeCorreio1)
                            .addComponent(rbtnDepositoBancario1))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtNameSalaried, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtAddressSalaried, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDSalaried, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalarySalaried, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMethodSalaried, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnChequeCorreio1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnChequeMaos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnDepositoBancario1)
                .addGap(17, 17, 17)
                .addComponent(rbtnSyndSalaried)
                .addGap(16, 16, 16)
                .addComponent(bntAddSalaried)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNameSalaried, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAddressSalaried, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(300, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Assalariado", jPanel1);

        jLabel18.setText("Nome:");

        bntAddHourly.setText("Adicionar");
        bntAddHourly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddHourlyActionPerformed(evt);
            }
        });

        txtNameHourly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameHourlyActionPerformed(evt);
            }
        });

        jLabel19.setText("Salario");

        jLabel20.setText("Endereço");

        jLabel22.setText("CPF");

        rbtnSyndHourly.setText("Sindicato");
        rbtnSyndHourly.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtMethodHourly.setEditable(false);
        txtMethodHourly.setText("semanalmente");
        txtMethodHourly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMethodHourlyActionPerformed(evt);
            }
        });

        jLabel25.setText("Metodo");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel26.setText("Pagamento via:");

        rbtnDepositoBancario2.setText("Deposito Bancario");
        rbtnDepositoBancario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDepositoBancario2ActionPerformed(evt);
            }
        });

        rbtnChequeMaos2.setText("Cheque em mãos");
        rbtnChequeMaos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnChequeMaos2ActionPerformed(evt);
            }
        });

        rbtnChequeCorreio2.setText("Cheque pelos correios");
        rbtnChequeCorreio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnChequeCorreio2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSalaryHourly, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMethodHourly, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddressHourly, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDHourly, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameHourly, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnChequeMaos2)
                            .addComponent(rbtnChequeCorreio2)
                            .addComponent(rbtnDepositoBancario2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(bntAddHourly))
                    .addComponent(rbtnSyndHourly))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameHourly, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddressHourly, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDHourly, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalaryHourly, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMethodHourly, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbtnChequeCorreio2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnChequeMaos2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnDepositoBancario2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(rbtnSyndHourly)
                .addGap(17, 17, 17)
                .addComponent(bntAddHourly)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Horista", jPanel3);

        txtCommission.setText("0.0");
        txtCommission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommissionActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome:");

        bntAddCommissioned.setText("Adicionar");
        bntAddCommissioned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddCommissionedActionPerformed(evt);
            }
        });

        jLabel8.setText("Salario");

        jLabel9.setText("Endereço");

        jLabel11.setText("CPF");

        rbtnSyndCommissioned.setText("Sindicato");
        rbtnSyndCommissioned.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rbtnSyndCommissioned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSyndCommissionedActionPerformed(evt);
            }
        });

        jLabel12.setText("Comissão(%)");

        jLabel24.setText("Metodo");

        txtMethodCommissioned.setEditable(false);
        txtMethodCommissioned.setText("bi- semanalmente");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel28.setText("Pagamento via:");

        rbtnDepositoBancario3.setText("Deposito Bancario");
        rbtnDepositoBancario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDepositoBancario3ActionPerformed(evt);
            }
        });

        rbtnChequeMaos3.setText("Cheque em mãos");
        rbtnChequeMaos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnChequeMaos3ActionPerformed(evt);
            }
        });

        rbtnChequeCorreio3.setText("Cheque pelos correios");
        rbtnChequeCorreio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnChequeCorreio3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSalaryCommissioned, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMethodCommissioned, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCommission, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddressCommissioned, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIDCommissioned, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNameCommissioned, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnSyndCommissioned))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnChequeMaos3)
                                    .addComponent(rbtnChequeCorreio3)
                                    .addComponent(rbtnDepositoBancario3)
                                    .addComponent(bntAddCommissioned))))
                        .addContainerGap(36, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(204, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNameCommissioned, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAddressCommissioned, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDCommissioned, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalaryCommissioned, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMethodCommissioned, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCommission, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbtnChequeCorreio3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnChequeMaos3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnDepositoBancario3)
                        .addGap(17, 17, 17)
                        .addComponent(bntAddCommissioned))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(rbtnSyndCommissioned)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(300, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Comissionado", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCommissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommissionActionPerformed

    private void bntAddCommissionedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddCommissionedActionPerformed
        // TODO add your handling code here:
        if(qfmain.getIndex(txtIDCommissioned.getText()) == -1){
        Commissioned p = new Commissioned(Float.parseFloat(txtCommission.getText()),txtNameCommissioned.getText(),
                                  txtIDCommissioned.getText(),
                                  txtAddressCommissioned.getText(),rbtnSyndCommissioned.isSelected(),
                                  txtMethodCommissioned.getText(),Float.parseFloat(txtSalaryCommissioned.getText()));
        if(rbtnSyndSalaried.isSelected()){
            p.setSyndicateId("");
        }
        if(rbtnChequeCorreio3.isSelected()){
            p.setPaymentTransfer("Cheque pelos correios");
        }else if(rbtnChequeMaos3.isSelected()){
            p.setPaymentTransfer("Cheque em maõs");
        } else if(rbtnDepositoBancario3.isSelected()){
            p.setPaymentTransfer("Deposito Bancario");
        }else{
            JOptionPane.showMessageDialog(null,"Pagamento foi definido via: Deposito Bancario");
        }
        p.setDefault(qfmain.getDiaAtual());
        qfmain.add(p);
        
        String[] s = new String[]{txtNameCommissioned.getText(),txtAddressCommissioned.getText(),txtIDCommissioned.getText(),"Commissioned"};
        tablemain.addRow(s);
        this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Pagamento foi definido via: Deposito Bancario");
        }
    }//GEN-LAST:event_bntAddCommissionedActionPerformed

    private void bntAddSalariedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddSalariedActionPerformed
        //public Salaried(String name, String employeeID, String address, boolean Syndicate, String paymentMethod, float salary)
        
        if(qfmain.getIndex(txtIDSalaried.getText()) == -1){
        Salaried p = new Salaried(txtNameSalaried.getText(),txtIDSalaried.getText(),
                                  txtAddressSalaried.getText(),rbtnSyndSalaried.isSelected(),
                                  txtMethodSalaried.getText(),Float.parseFloat(txtSalarySalaried.getText()));
        if(rbtnSyndSalaried.isSelected()){
            p.setSyndicateId("");
        }
        if(rbtnChequeCorreio1.isSelected()){
            p.setPaymentTransfer("Cheque pelos correios");
        }else if(rbtnChequeMaos1.isSelected()){
            p.setPaymentTransfer("Cheque em maõs");
        } else if(rbtnDepositoBancario1.isSelected()){
            p.setPaymentTransfer("Deposito Bancario");
        }else{
            JOptionPane.showMessageDialog(null,"Pagamento foi definido via: Deposito Bancario");
        }
        p.setDefault(qfmain.getDiaAtual());
        qfmain.add(p);
        
        String[] s = new String[]{txtNameSalaried.getText(),txtAddressSalaried.getText(),txtIDSalaried.getText(),"salaried"};
        tablemain.addRow(s);
        this.dispose();
        }else {
            JOptionPane.showMessageDialog(null,"Ja existe um funcionario com esse Cpf");
        }
    }//GEN-LAST:event_bntAddSalariedActionPerformed

    private void bntAddHourlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddHourlyActionPerformed
        if(qfmain.getIndex(txtIDHourly.getText()) == -1){
        Hourly p = new Hourly(txtNameHourly.getText(),txtIDHourly.getText(),
                            txtAddressHourly.getText(),rbtnSyndHourly.isSelected(),
                            txtMethodHourly.getText(),Float.parseFloat(txtSalaryHourly.getText()));
        if(rbtnSyndSalaried.isSelected()){
            p.setSyndicateId("");
        }
        if(rbtnChequeCorreio2.isSelected()){
            p.setPaymentTransfer("Cheque pelos correios");
        }else if(rbtnChequeMaos2.isSelected()){
            p.setPaymentTransfer("Cheque em maõs");
        } else if(rbtnDepositoBancario2.isSelected()){
            p.setPaymentTransfer("Deposito Bancario");
        }else{
            JOptionPane.showMessageDialog(null,"Pagamento foi definido via: Deposito Bancario");
        }
        p.setDefault(qfmain.getDiaAtual());
        qfmain.add(p);

        String[] s = new String[]{txtNameHourly.getText(),txtAddressHourly.getText(),txtIDHourly.getText(),"Hourly"};
        tablemain.addRow(s);
        this.dispose();
        } else {
            JOptionPane.showMessageDialog(null,"Ja existe um funcionario com esse Cpf");
        }
    }//GEN-LAST:event_bntAddHourlyActionPerformed

    private void txtMethodHourlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMethodHourlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMethodHourlyActionPerformed

    private void txtMethodSalariedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMethodSalariedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMethodSalariedActionPerformed

    private void txtNameHourlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameHourlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameHourlyActionPerformed

    private void rbtnSyndSalariedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSyndSalariedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnSyndSalariedActionPerformed

    private void rbtnChequeCorreio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnChequeCorreio1ActionPerformed
        // TODO add your handling code here:
        rbtnChequeMaos1.setSelected(false);
        rbtnDepositoBancario1.setSelected(false);
    }//GEN-LAST:event_rbtnChequeCorreio1ActionPerformed

    private void rbtnChequeCorreio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnChequeCorreio2ActionPerformed
        // TODO add your handling code here:
        rbtnChequeMaos2.setSelected(false);
        rbtnDepositoBancario2.setSelected(false);
    }//GEN-LAST:event_rbtnChequeCorreio2ActionPerformed

    private void rbtnDepositoBancario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDepositoBancario2ActionPerformed
        // TODO add your handling code here:
        rbtnChequeCorreio2.setSelected(false);
        rbtnChequeMaos2.setSelected(false);
    }//GEN-LAST:event_rbtnDepositoBancario2ActionPerformed

    private void rbtnDepositoBancario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDepositoBancario3ActionPerformed
        // TODO add your handling code here:
        rbtnChequeCorreio3.setSelected(false);
        rbtnChequeMaos3.setSelected(false);
    }//GEN-LAST:event_rbtnDepositoBancario3ActionPerformed

    private void rbtnChequeCorreio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnChequeCorreio3ActionPerformed
        // TODO add your handling code here:
        rbtnChequeMaos3.setSelected(false);
        rbtnDepositoBancario3.setSelected(false);
                
    }//GEN-LAST:event_rbtnChequeCorreio3ActionPerformed

    private void rbtnSyndCommissionedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSyndCommissionedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnSyndCommissionedActionPerformed

    private void rbtnChequeMaos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnChequeMaos3ActionPerformed
        // TODO add your handling code here:
        rbtnChequeCorreio3.setSelected(false);
        rbtnDepositoBancario3.setSelected(false);
    }//GEN-LAST:event_rbtnChequeMaos3ActionPerformed

    private void rbtnChequeMaos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnChequeMaos2ActionPerformed
        // TODO add your handling code here:
        rbtnChequeCorreio2.setSelected(false);
        rbtnDepositoBancario2.setSelected(false);
    }//GEN-LAST:event_rbtnChequeMaos2ActionPerformed

    private void rbtnChequeMaos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnChequeMaos1ActionPerformed
        // TODO add your handling code here:
        rbtnChequeCorreio1.setSelected(false);
        rbtnDepositoBancario1.setSelected(false);
    }//GEN-LAST:event_rbtnChequeMaos1ActionPerformed

    private void rbtnDepositoBancario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDepositoBancario1ActionPerformed
        // TODO add your handling code here:
        rbtnChequeCorreio1.setSelected(false);
        rbtnChequeMaos1.setSelected(false);;
    }//GEN-LAST:event_rbtnDepositoBancario1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAddCommissioned;
    private javax.swing.JButton bntAddHourly;
    private javax.swing.JButton bntAddSalaried;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rbtnChequeCorreio1;
    private javax.swing.JRadioButton rbtnChequeCorreio2;
    private javax.swing.JRadioButton rbtnChequeCorreio3;
    private javax.swing.JRadioButton rbtnChequeMaos1;
    private javax.swing.JRadioButton rbtnChequeMaos2;
    private javax.swing.JRadioButton rbtnChequeMaos3;
    private javax.swing.JRadioButton rbtnDepositoBancario1;
    private javax.swing.JRadioButton rbtnDepositoBancario2;
    private javax.swing.JRadioButton rbtnDepositoBancario3;
    private javax.swing.JRadioButton rbtnSyndCommissioned;
    private javax.swing.JRadioButton rbtnSyndHourly;
    private javax.swing.JRadioButton rbtnSyndSalaried;
    private javax.swing.JTextField txtAddressCommissioned;
    private javax.swing.JTextField txtAddressHourly;
    private javax.swing.JTextField txtAddressSalaried;
    private javax.swing.JTextField txtCommission;
    private javax.swing.JTextField txtIDCommissioned;
    private javax.swing.JTextField txtIDHourly;
    private javax.swing.JTextField txtIDSalaried;
    private javax.swing.JTextField txtMethodCommissioned;
    private javax.swing.JTextField txtMethodHourly;
    private javax.swing.JTextField txtMethodSalaried;
    private javax.swing.JTextField txtNameCommissioned;
    private javax.swing.JTextField txtNameHourly;
    private javax.swing.JTextField txtNameSalaried;
    private javax.swing.JTextField txtSalaryCommissioned;
    private javax.swing.JTextField txtSalaryHourly;
    private javax.swing.JTextField txtSalarySalaried;
    // End of variables declaration//GEN-END:variables
}
