/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetodesoftware.Commissioned;
import projetodesoftware.Funcionario;
import projetodesoftware.Hourly;
import projetodesoftware.QuadrodeFuncionarios;
import projetodesoftware.Salaried;

/**
 *
 * @author Rangel
 */
public class EditEmployee extends javax.swing.JFrame {

    /**
     * Creates new form EditEmployee
     */
    
    QuadrodeFuncionarios qfmain = new QuadrodeFuncionarios();
    DefaultTableModel tablemain;
    
    public EditEmployee() {
        initComponents();
    }
    
    public void importQuandroF(QuadrodeFuncionarios qf, DefaultTableModel table){
        qfmain = qf;
        tablemain = table;
    }
    
    void changeTable(DefaultTableModel table, String[] s, int i){
        for(int k = 0; k < 4 ;  k++){
            table.setValueAt(s[k], i, k);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUnionFee = new javax.swing.JLabel();
        txtUnionFee = new javax.swing.JTextField();
        lblIdSind = new javax.swing.JLabel();
        txtIdSind = new javax.swing.JTextField();
        rbtnSynd = new javax.swing.JRadioButton();
        btbEdit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rbtnSalaried = new javax.swing.JRadioButton();
        rbtnCommissioned = new javax.swing.JRadioButton();
        rbtnHourly = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtCommission = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblDia_semana = new javax.swing.JLabel();
        txtDiaNSemanas = new javax.swing.JTextField();
        txtDiaSemana = new javax.swing.JTextField();
        lblDiaSemana = new javax.swing.JLabel();
        rbtnMensal = new javax.swing.JRadioButton();
        rbtnSemanal = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearch.setText("CPF do Funcionario");

        btnSearch.setText("Pesquisar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Endereço:");

        jLabel3.setText("Salario");

        jLabel4.setText("Tipo:");

        lblUnionFee.setText("Taxa Sindical:");

        txtUnionFee.setText("0.0");
        txtUnionFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnionFeeActionPerformed(evt);
            }
        });

        lblIdSind.setText("Id Sindical:");

        rbtnSynd.setText("Sindicato");

        btbEdit.setText("Editar");
        btbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbEditActionPerformed(evt);
            }
        });

        jLabel5.setText("Método");

        rbtnSalaried.setText("Assalariado");
        rbtnSalaried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSalariedActionPerformed(evt);
            }
        });

        rbtnCommissioned.setText("Comissionado");
        rbtnCommissioned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCommissionedActionPerformed(evt);
            }
        });

        rbtnHourly.setText("Horista");
        rbtnHourly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnHourlyActionPerformed(evt);
            }
        });

        jLabel6.setText("Comissão(%):");

        lblDia_semana.setText("Dia/nSamanas");

        txtDiaNSemanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaNSemanasActionPerformed(evt);
            }
        });

        lblDiaSemana.setText("Dia da semana");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblDia_semana))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDiaSemana)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaNSemanas, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDia_semana)
                    .addComponent(txtDiaNSemanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaSemana))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rbtnMensal.setText("Mensal");
        rbtnMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMensalActionPerformed(evt);
            }
        });

        rbtnSemanal.setText("Semanal");
        rbtnSemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSemanalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btbEdit))
                    .addComponent(rbtnSynd)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUnionFee, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUnionFee, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIdSind, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdSind, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnHourly)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtnSalaried)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnCommissioned))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(rbtnMensal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnSemanal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCommission, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbtnMensal)
                    .addComponent(rbtnSemanal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCommission, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnSalaried)
                            .addComponent(rbtnCommissioned))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnHourly))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnSynd)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnionFee)
                    .addComponent(txtUnionFee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdSind)
                    .addComponent(txtIdSind, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btbEdit)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        int i = qfmain.getIndex(txtSearch.getText());
        if(qfmain.f.get(i) instanceof Commissioned commissioned){
            
            txtCommission.setText(String.valueOf(commissioned.getCommission()));
        }
        if(i!=-1){
            txtName.setText(qfmain.f.get(i).getName());
            txtAddress.setText(qfmain.f.get(i).getAddress());
            txtSalary.setText(String.valueOf(qfmain.f.get(i).getSalary()));
            if(qfmain.f.get(i).getPaymentMethod().equals("mensal") || qfmain.f.get(i).getPaymentMethod().equals("mensalmente")){
                rbtnMensal.setSelected(true);
                rbtnSemanal.setSelected(false);
                txtDiaNSemanas.setText(qfmain.f.get(i).getTimePaymentMethod());
            } else if(qfmain.f.get(i).getPaymentMethod().equals("semanal") || qfmain.f.get(i).getPaymentMethod().equals("semanalmente")){
                rbtnMensal.setSelected(false);
                rbtnSemanal.setSelected(true);
                txtDiaNSemanas.setText(qfmain.f.get(i).getTimePaymentMethod());
                txtDiaSemana.setText(qfmain.f.get(i).getTimeMethodWeekDay());
            }
            //txtPaymentMethod.setText(qfmain.f.get(i).getPaymentMethod());
            if(qfmain.f.get(i).isSyndicate()){
                rbtnSynd.setSelected(true);
                txtUnionFee.setText(Float.toString(qfmain.f.get(i).getUnionFee()));
                txtIdSind.setText(qfmain.f.get(i).getSyndicateId());
            }else {
                //rbtnSynd.setSelected(false);
                //txtUnionFee.setVisible(false);
                //txtIdSind.setVisible(false);
                //lblUnionFee.setVisible(false);
                //lblIdSind.setVisible(false);
            }
            if(qfmain.f.get(i) instanceof Salaried){
                    rbtnSalaried.setSelected(true);
                    rbtnCommissioned.setSelected(false);
                    rbtnHourly.setSelected(false);
               } else if(qfmain.f.get(i) instanceof Commissioned){
                    rbtnSalaried.setSelected(false);
                    rbtnCommissioned.setSelected(true);
                    rbtnHourly.setSelected(false);
               }else if (qfmain.f.get(i) instanceof Hourly){
                    rbtnSalaried.setSelected(false);
                    rbtnCommissioned.setSelected(false);
                    rbtnHourly.setSelected(true);
               }
            
        } else {
            JOptionPane.showMessageDialog(null,"Funcionario nao encontrado");
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbEditActionPerformed
        
        String confereAgenda;
        //
        String cpf = txtSearch.getText();
        Funcionario p;
        int i = qfmain.getIndex(txtSearch.getText());
        String type = "";
        String Method="",timeMethod="",timeMethodWeekDay="";
        if(rbtnMensal.isSelected()){
            //p.setPaymentMethod("mensalmente", txtDiaNSemanas.getText(), "");
            Method = "mensalmente";
            timeMethod=txtDiaNSemanas.getText();
            if(!timeMethod.equals("")){
                Method = "mensal";
            }
            timeMethodWeekDay = "";
        } else if(rbtnSemanal.isSelected()){
            //p.setPaymentMethod("semanalmente", txtDiaNSemanas.getText(), txtDiaSemana.getText());
            Method = "semanalmente";
            timeMethod=txtDiaNSemanas.getText();
            if(!timeMethod.equals("")){
                Method = "semanal";
            }
            timeMethodWeekDay=txtDiaSemana.getText();
        }
        confereAgenda = Method;
        if(!timeMethod.equals("") && timeMethod != null){
            confereAgenda += " "+timeMethod;
        } else{
            timeMethod = "";
        }
        if(!timeMethodWeekDay.equals("")&& timeMethodWeekDay!=null){
            confereAgenda += " "+timeMethodWeekDay;
        }else{
            timeMethodWeekDay = "";
        }
        if(!qfmain.ap.existAgenda(confereAgenda)){
            System.out.println(confereAgenda);
            JOptionPane.showMessageDialog(null,"Agenda de pagamento não é valida");
        }else{
        if(rbtnSalaried.isSelected()){
            p = new Salaried();
            p.setEmployeeID(cpf);
            p.setName(txtName.getText());
            p.setAddress(txtAddress.getText());
            p.setSalary(Float.parseFloat(txtSalary.getText()));
            p.setType("Salaried");
            if(rbtnMensal.isSelected()){
                //p.setPaymentMethod("mensalmente", txtDiaNSemanas.getText(), "");
                Method = "mensalmente";
                timeMethod=txtDiaNSemanas.getText();
            } else if(rbtnSemanal.isSelected()){
                //p.setPaymentMethod("semanalmente", txtDiaNSemanas.getText(), txtDiaSemana.getText());
                Method = "semanalmente";
                timeMethod=txtDiaNSemanas.getText();
                timeMethodWeekDay=txtDiaSemana.getText();
            }
            if(rbtnSynd.isSelected()){
                p.setSyndicate(true);
                p.setUnionFee(Float.parseFloat(txtUnionFee.getText()));
                p.setSyndicateId(txtIdSind.getText());
            }
            //p.setPaymentMethod(txtSalary.getText());
            
            p = (Salaried)p;
            qfmain.changeDetails(cpf, p);
            qfmain.AlterarAgandaFuncionario(cpf, Method, timeMethod, timeMethodWeekDay);
            type = "Salaried";
        }else if(rbtnCommissioned.isSelected())
        {
            p = new Commissioned();
            p.setEmployeeID(cpf);
            p.setName(txtName.getText());
            p.setAddress(txtAddress.getText());
            p.setSalary(Float.parseFloat(txtSalary.getText()));
            p.setType("Commissioned");
            /*if(rbtnMensal.isSelected()){
                //p.setPaymentMethod("mensalmente", txtDiaNSemanas.getText(), "");
                Method = "mensalmente";
                timeMethod=txtDiaNSemanas.getText();
            } else if(rbtnSemanal.isSelected()){
                //p.setPaymentMethod("semanalmente", txtDiaNSemanas.getText(), txtDiaSemana.getText());
                Method = "semanalmente";
                timeMethod=txtDiaNSemanas.getText();
                timeMethodWeekDay=txtDiaSemana.getText();
            }*/
            if(rbtnSynd.isSelected()){
                p.setSyndicate(true);
                p.setUnionFee(Float.parseFloat(txtUnionFee.getText()));
                p.setSyndicateId(txtIdSind.getText());
            }
            //p.setPaymentMethod(txtSalary.getText());
            
            
            if (qfmain.f.get(i) instanceof Commissioned && txtCommission.getText().equals(""))
            {
                ((Commissioned)p).setCommission(((Commissioned)qfmain.f.get(i)).getCommission());
            }else{
                ((Commissioned)p).setCommission(Float.parseFloat(txtCommission.getText()));
            }
            
            p = (Commissioned)p;
            qfmain.changeDetails(cpf, p);
            qfmain.AlterarAgandaFuncionario(cpf, Method, timeMethod, timeMethodWeekDay);
            type = "Commissioned";
            
        }else if(rbtnHourly.isSelected()){
            p = new Hourly();
            p.setEmployeeID(cpf);
            p.setName(txtName.getText());
            p.setAddress(txtAddress.getText());
            p.setSalary(Float.parseFloat(txtSalary.getText()));
            p.setType("Hourly");
            /*if(rbtnMensal.isSelected()){
                //p.setPaymentMethod("mensalmente", txtDiaNSemanas.getText(), "");
                Method = "mensalmente";
                timeMethod=txtDiaNSemanas.getText();
            } else if(rbtnSemanal.isSelected()){
                //p.setPaymentMethod("semanalmente", txtDiaNSemanas.getText(), txtDiaSemana.getText());
                Method = "semanalmente";
                timeMethod=txtDiaNSemanas.getText();
                timeMethodWeekDay=txtDiaSemana.getText();
            }*/
            if(rbtnSynd.isSelected()){
                p.setSyndicate(true);
                p.setUnionFee(Float.parseFloat(txtUnionFee.getText()));
                p.setSyndicateId(txtIdSind.getText());
            }
            //p.setPaymentMethod(txtSalary.getText());
            
            if(qfmain.f.get(i) instanceof Hourly)
                {
                    //((Hourly)p).setWorkedhours(((Hourly)qfmain.f.get(i)).getWorkedhours());
                    ((Hourly)p).workedhours = ((Hourly)qfmain.f.get(i)).workedhours;
                }
            p = (Hourly) p;
            type = "Hourly";
            qfmain.changeDetails(cpf, p);
            qfmain.AlterarAgandaFuncionario(cpf, Method, timeMethod, timeMethodWeekDay);
        }
        
        String[] s = {txtName.getText(),txtAddress.getText(),txtSearch.getText(), type};
        changeTable(tablemain,s, i);
        this.dispose();
     }
    }//GEN-LAST:event_btbEditActionPerformed

    private void txtUnionFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnionFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnionFeeActionPerformed

    private void rbtnSalariedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSalariedActionPerformed
        // TODO add your handling code here:
        rbtnSalaried.setSelected(true);
        rbtnCommissioned.setSelected(false);
        rbtnHourly.setSelected(false);
    }//GEN-LAST:event_rbtnSalariedActionPerformed

    private void rbtnCommissionedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCommissionedActionPerformed
        // TODO add your handling code here:
        rbtnSalaried.setSelected(false);
        rbtnCommissioned.setSelected(true);
        rbtnHourly.setSelected(false);
    }//GEN-LAST:event_rbtnCommissionedActionPerformed

    private void rbtnHourlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnHourlyActionPerformed
        // TODO add your handling code here:
        rbtnSalaried.setSelected(false);
        rbtnCommissioned.setSelected(false);
        rbtnHourly.setSelected(true);
    }//GEN-LAST:event_rbtnHourlyActionPerformed

    private void txtDiaNSemanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaNSemanasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaNSemanasActionPerformed

    private void rbtnSemanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSemanalActionPerformed
        // TODO add your handling code here:
        if(rbtnSemanal.isSelected()){
            rbtnMensal.setSelected(false);
            txtDiaSemana.setVisible(true);
            lblDiaSemana.setVisible(true);
            lblDia_semana.setText("Semanas:");
        }
    }//GEN-LAST:event_rbtnSemanalActionPerformed

    private void rbtnMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMensalActionPerformed
        // TODO add your handling code here:
        if(rbtnMensal.isSelected()){
            rbtnSemanal.setSelected(false);
            txtDiaSemana.setVisible(false);
            lblDiaSemana.setVisible(false);
            lblDia_semana.setText("     Dia:     ");
        }
    }//GEN-LAST:event_rbtnMensalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lblDiaSemana;
    private javax.swing.JLabel lblDia_semana;
    private javax.swing.JLabel lblIdSind;
    private javax.swing.JLabel lblUnionFee;
    private javax.swing.JRadioButton rbtnCommissioned;
    private javax.swing.JRadioButton rbtnHourly;
    private javax.swing.JRadioButton rbtnMensal;
    private javax.swing.JRadioButton rbtnSalaried;
    private javax.swing.JRadioButton rbtnSemanal;
    private javax.swing.JRadioButton rbtnSynd;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCommission;
    private javax.swing.JTextField txtDiaNSemanas;
    private javax.swing.JTextField txtDiaSemana;
    private javax.swing.JTextField txtIdSind;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUnionFee;
    // End of variables declaration//GEN-END:variables
}
